### ISSUE TITLE
Roadmap: Upgrade to react-admin v5

### ISSUE THREAD

**Issue by awesome-manuel** [Awesome-Technologies/synapse-admin#584]
See https://marmelab.com/react-admin/Upgrade.html

- [x] React 18
- [ ] Use @tanstack/react-query instead of react-query
- [ ] Inputs Have Full Width By Default -> remove `fullWidth` prop
- [ ] Links are now underlined by default -> must be checked
- [ ] Dark Theme Is Available By Default -> remove `darkTheme` prop
- [ ] List Components Can No Longer Be Used In Standalone -> check login page
- [ ] `<Datagrid rowClick>` is no longer false by default -> check
- [ ] TypeScript -> enable `strictNullChecks`
- [ ] useRecordContext Returns undefined When No Record Is Available
- [ ] useAuthProvider Returns undefined When No authProvider Is Available
